### ISSUE TITLE
Elección de Temas

### ISSUE THREAD

**Issue by codeMariana** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-rrmiguel-2401#2]
- [x] Se discuten temas de análisis del proyecto.
- [x] Se escoge el tema del proyecto.
- [x] Se justifica la elección del tema de acuerdo con trabajos previos realizados.
- [x] Se escoge el método de análisis visto en clase.

**Comment by rrmiguel-2401** [comment]
Cerrando issue #2
